NODE_ENV=production
PORT=8080

DB_NAME=postgres
DB_USERNAME=postgres
DB_PASSWORD=foodbackdatabase
DB_HOST=34.101.111.160
DB_DIALECT=postgres

API_KEY_FOOD=d41748bedca54cdd9bf570d97bbd8cd5
API_KEY_EXERCISE="UyYJTjO9IdIE7YZhUIHRNw==fe8XRZtxhl0R5qAg"
